name: Build and Package WinUI 3 App

on:
  push:
    branches: [master]

jobs:
  build-and-sign:
    runs-on: windows-latest
    name: Build app and sign files with Trusted Signing

    strategy:
      matrix:
        configuration: [Release]
        platform: [x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: msbuild -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }}

     
